# Generated by Django 4.2.15 on 2024-09-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
